# CNB 配置文件 - 1Panel v2 离线安装包构建
# 对应 GitHub Actions: .github/workflows/build-offline-v2.yml
#
# 环境变量说明 (通过手动触发时可传入):
#   MODE: stable | beta | dev (默认: stable)
#   INPUT_VERSION: 1Panel版本号 (如 v2.0.13, 留空则自动获取最新)
#   FORCE_BUILD: 设为1强制构建，即使版本已存在

# 定义构建流水线模板（复用）
.build_pipeline: &build_pipeline
  - name: Build 1Panel v2 Offline
    runner:
      tags: cnb:arch:amd64
      cpus: 4
    docker:
      image: ubuntu:22.04
    services:
      - docker
    stages:
      - name: Install dependencies
        script: |
          apt-get update
          apt-get install -y curl jq python3 git

      - name: Check Version
        script: |
          set -e
          mode="${MODE:-stable}"
          input_version="${INPUT_VERSION:-}"

          # 获取1Panel版本
          if [ -n "$input_version" ]; then
            version="$input_version"
          else
            version=$(curl -s "https://resource.fit2cloud.com/1panel/package/v2/${mode}/latest")
          fi
          if [ -z "${version}" ] || [ "${version}" = "null" ]; then
            echo "Failed to get 1Panel version"
            exit 1
          fi

          # 检查是否已构建过此版本 (通过检查release tag是否存在)
          skip_build="0"
          if [ "${FORCE_BUILD:-0}" != "1" ]; then
            if git ls-remote --tags origin | grep -q "refs/tags/${version}$"; then
              echo "Version ${version} already released (tag exists), skipping..."
              skip_build="1"
            fi
          fi

          # 获取Docker版本 (带fallback)
          raw_docker_version=$(curl -s 'https://api.github.com/repos/moby/moby/releases/latest' | jq -r ".tag_name // empty")
          docker_version=${raw_docker_version#docker-}
          docker_version=${docker_version#v}
          if [ -z "${docker_version}" ] || [ "${docker_version}" = "null" ]; then
            docker_version="27.3.1"
            echo "WARN: Failed to get Docker version, using fallback: ${docker_version}"
          fi

          # 获取Compose版本 (带fallback)
          compose_version=$(curl -s 'https://api.github.com/repos/docker/compose/releases/latest' | jq -r ".tag_name // empty")
          if [ -z "${compose_version}" ] || [ "${compose_version}" = "null" ]; then
            compose_version="v2.30.3"
            echo "WARN: Failed to get Compose version, using fallback: ${compose_version}"
          fi

          echo "1Panel: ${version}, mode: ${mode}, docker: ${docker_version}, compose: ${compose_version}, skip: ${skip_build}"

          echo "##[set-output VERSION=${version}]"
          echo "##[set-output BUILD_MODE=${mode}]"
          echo "##[set-output DOCKER_VERSION=${docker_version}]"
          echo "##[set-output COMPOSE_VERSION=${compose_version}]"
          echo "##[set-output SKIP_BUILD=${skip_build}]"
        exports:
          VERSION: VERSION
          BUILD_MODE: BUILD_MODE
          DOCKER_VERSION: DOCKER_VERSION
          COMPOSE_VERSION: COMPOSE_VERSION
          SKIP_BUILD: SKIP_BUILD

      - name: Build Offline Packages
        if: test "$SKIP_BUILD" != "1"
        script: |
          set -e
          chmod +x prepare_offline.sh
          ./prepare_offline.sh \
            --mode "${BUILD_MODE}" \
            --app_version "${VERSION}" \
            --docker_version "${DOCKER_VERSION}" \
            --compose_version "${COMPOSE_VERSION}" \
            --allow-missing

      - name: Create Tag and Release
        if: test "$SKIP_BUILD" != "1"
        script: |
          set -e
          git config --global user.name "CNB Bot"
          git config --global user.email "bot@cnb.cool"
          # 创建版本tag
          git tag -f "${VERSION}" -m "Release ${VERSION}"
          git push origin "refs/tags/${VERSION}" -f || true

      - name: Create CNB Release
        if: test "$SKIP_BUILD" != "1"
        type: git:release
        options:
          tag: ${VERSION}
          title: ${VERSION}
          description: "1Panel v2 离线安装包 (mode: ${BUILD_MODE})"
          overlying: true

      - name: Upload to CNB Release
        if: test "$SKIP_BUILD" != "1"
        image: cnbcool/attachments:latest
        settings:
          tag: ${VERSION}
          attachments:
            - build/${VERSION}/checksums.txt
            - build/${VERSION}/*/*.tar.gz

# ============================================
# 触发规则配置
# ============================================

# master 分支配置
master:
  # Push 事件触发
  push: *build_pipeline

  # 定时任务 - 每天 UTC 03:00 (北京时间 11:00)
  "crontab: 0 3 * * *": *build_pipeline

  # 手动触发 (对应 .cnb/web_trigger.yml 中的 event)
  web_trigger_build: *build_pipeline
